name: Bocho-community

on:
  push:
    branches: ["develop"]
  pull_request:
    branches: ["develop"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 깃헙 레포지토리에 올린 파일 불러오기
        uses: actions/checkout@v4

      - name: sudo 권한 주기
        run: sudo -s

      - name: Install JAVA
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: gradlew 실행 권한 주기
        run: chmod +x gradlew

      - name: application.properties 파일 만들기
        run: echo "${{ secrets.APPLICATION_PROPERTIES }}" > src/main/resources/application.properties

      - name: 테스트 및 빌드
        run: ./gradlew clean build

      - name: 빌드된 파일 이름 변경
        run: mv ./build/libs/*SNAPSHOT.jar ./project.jar

      - name: transfer jar file using scp
        uses: appleboy/scp-action@master
        with:
          host : ${{ secrets.EC2_IP }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          source: project.jar
          target: /home/ec2-user/back/tobe

      - name: connect to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_IP }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script_stop: true
          script: |
            rm -rf /home/ec2-user/back/current
            mkdir /home/ec2-user/back/current
            mv /home/ec2-user/back/tobe/project.jar /home/ec2-user/back/current/project.jar
            cd /home/ec2-user/back/current
            sudo fuser -k -n tcp 3000 || true
            nohup java -jar project.jar > ./output.log 2>&1 & 
            rm -rf /home/ec2-user/back/tobe
