name: Bocho-community

on:
  push:
    branches: ["feature/docker-ecr"]
  pull_request:
    branches: ["develop"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 깃헙 레포지토리에 올린 파일 불러오기
        uses: actions/checkout@v4

      - name : JDK 17버전 설치
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: application.properties 파일 만들기
        run: echo "${{ secrets.APPLICATION_PROPERTIES }}" > src/main/resources/application.properties

      - name: gradlew 실행 권한 주기
        run: chmod +x gradlew

      - name: 테스트 및 빌드
        run: ./gradlew clean build

      - name: AWS Resource에 접근할 수 있게 AWS credentials 설정
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ap-northeast-2
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Login to ECR
        id : login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Docker 이미지 생성
        run: docker build -t bocho-drive .

      - name: Docker 이미지에 Tag 붙이기
        run: docker tag bocho-drive ${{ steps.login-ecr.outputs.registry }}/bocho-drive:latest

      - name : ECR에 도커 이미지 push
        run : docker push ${{ steps.login-ecr.outputs.registry }}/bocho-drive:latest

      - name: connect to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_IP }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script_stop: true
          script: |
            docker stop bocho-drive || true
            docker rm bocho-drive || true
            docker pull ${{ steps.login-ecr.outputs.registry }}/bocho-drive:latest
            docker run -d --name bochodrive -p 3000:3000 ${{ steps.login-ecr.outputs.registry }}/bocho-drive:latest